version: '3.8'

networks:
  website-net:

volumes:
  db-data:

services:
  website:
    build: .
    container_name: gulf_traject_web
    networks:
      - website-net
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: gulf_traject_db
    restart: always
    environment:
      - POSTGRES_USER=yanis
      - POSTGRES_PASSWORD=a
      - POSTGRES_DB=db
    networks:
      - website-net
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
