networks:
  website-net:

volumes:
  db:

services:
  website:
    image: apache:latest
    container_name: apache
    networks:
      - website-net
    volumes:
      - /home/yanis/Documents/cours/A3/S6/Projets/Projetweb_Groupe12:/var/www/html
    ports:
      - "8080:80"

  db:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=yanis
      - POSTGRES_PASSWORD=a
      - POSTGRES_DB=db
    networks:
      - website-net
    volumes:
      - db:/var/lib/postgres/data
    ports:
      - "5432:5432"

